[workspace]
resolver = "2"
members = [
    "bsmap",
    # "methratio",
    # "methdiff",
    # "bsp2sam",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["BSMAP-rs contributors"]

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
clap_lex = "=1.0.7"
anyhow = "1"
thiserror = "2"
rayon = "1"
crossbeam-channel = "0.5"
flate2 = "1"
needletail = "0.6"
noodles = "0.83"
log = "0.4"
env_logger = "0.11"
indicatif = "0.17"
serde = { version = "1", features = ["derive"] }
bincode = "1"
memmap2 = "0.9"

[workspace.dev-dependencies]
criterion = "0.5"
tempfile = "3"
